#!/bin/sh

# PROVIDE: circusd
# REQUIRE: LOGIN postgres
# KEYWORD: shutdown

. /etc/rc.subr

name="circusd"
rcvar=circusd_enable

start_cmd="${name}_start"
stop_cmd=":"

load_rc_config $name

: ${circusd_enable="NO"}
: ${circusd_config="/home/hipparchia/hipparchia_venv/HipparchiaBSD/circusd.ini"}

command="/home/hipparchia/hipparchia_venv/bin/circusd"

circusd_start()
{
  echo "Starting circusd"
  sudo -u hipparchia ${command} --daemon ${circusd_config}
}

required_files="${circusd_config}"

load_rc_config $name

run_rc_command "$1"